### ISSUE TITLE
disable guys bot

### ISSUE THREAD

**Issue by violinofsmall** [zatech/site#5]
please update the site to disable guys bot or extend it to support hey gals. the community seems to think disabling it is the best option. it can easily be updated by changing the feature flag here: https://github.com/zatech/site/blob/main/config/features.php which is controlled by the aforementioned env var.

see the vote from the community here; https://zatech.slack.com/archives/C03A23LKM/p1667231222463339

![image](https://user-images.githubusercontent.com/112576265/199058209-8683ffaf-136b-4eb2-a689-f532ec1f86c2.png)

the votes are overwhelmingly in favor of disabling it. although few think extending it to be realistically inclusive is also an option.

**Comment by hevisko** [comment]
The vocal minority was pushing for this, the interesting part I believe they aren't much active on zatech anymore...

That said, I am also of the believe that this guys bot is/was one of the reasons that people got fed up with the admin/zatech structures and left.

Will this be disabled? I doubt it as it's a political correctness that keeps an extremely vocal minority quite and the admins is then less harrassed thus they don't want to be harrassed by that vocal minority to have peacefull sleeps

**Comment by n1c** [comment]
[Quotes are from this comment](https://zatech.slack.com/archives/C1N2YMB4N/p1667235217356049?thread_ts=1667233192.459769&cid=C1N2YMB4N)

> I mean, we could extend the bot to do what was originally intended as pointed out

It was originally a Slackbot auto-response ([along these lines](https://slack.com/resources/using-slack/a-guide-to-slackbot-custom-responses#:~:text=Light%20reminders)) that did exactly the same matches, but just sent a message that everyone could see instead of the current ephemeral message system.

> it should include hey guys, hey gals and other languages, I think that was mentioned as an alternative

We're happy with the current strings we use to match. It can't ever be perfect, this implementation is considered _good enough_. It's not supposed to solve all problems, simply a light reminder or nudge that language can have different meanings to different people.

We're well aware that not everyone (and probably a majority of people) don't feel the same way. The point is that there are people who do, and their voices are important.

> its truly ok to not even be called out by calling someone a racist or any other foul word on this slack but only actively encourage on subset of policing

This is a separate issue which you're also misrepresenting, you're welcome to chat to the admin team about it separately.

> I opened the PR based on the votes.

Just for the record, the bot will never be disabled / enabled based on a vote. It misses the point that it's supposed to encourage thinking about _a minority of people, that often go unheard_.

> in any case, no point in engaging this topic further. a suggestion to avoid duplicate conversations over and over again might be a decision log you could call back to 

Fair, we can use this issue as the history.

**Comment by hevisko** [comment]
> We're well aware that not everyone (and probably a majority of people) don't feel the same way. The point is that there are people who do, and their voices are important.

Thus, the majority has to bend to the wills of minorities.
That is a showing of fascism, not democracy ;)
 
> Just for the record, the bot will never be disabled / enabled based on a vote. It misses the point that it's supposed to encourage thinking about _a minority of people, that often go unheard_.

Rather: A minority that VERY vocally made a point to make others follow their way.

But that's how life works, you want to join a community, you bend to the rules as declared by the community's admins ;)

**Comment by n1c** [comment]
I don't think we'll reach some sort of magical conclusion that satisfies the way you see it. It's not an engineering problem that needs quantifying, solving etc.

I have personally spoken to more than zero people who appreciate the existence of the bot. This number is enough for me.

I don't think I have any more to add to this discussion.
